# Hyprland base config for predator.
# This file is managed by Home Manager.

$mod = SUPER
$terminal = kitty
$fileManager = nautilus
$browser = firefox
$editor = zeditor
$code = code

monitor = , preferred, auto, auto

env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORMTHEME,gtk3
env = QT_QPA_PLATFORMTHEME_QT6,gtk3

general {
    gaps_in = 5
    gaps_out = 0
    border_size = 2
    col.active_border = rgb(b4befe)
    col.inactive_border = rgb(8d9199)
    resize_on_border = false
    allow_tearing = false
    layout = scrolling
}

decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = rgba(00000077)
    }
}

animations {
    enabled = yes
    animation = border, 1, 5, default
    animation = windows, 1, 4, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, default
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = -1
    vrr = 2
}

input {
    kb_layout = us
    kb_variant = alt-intl
    kb_model = pc105
    kb_options =
    kb_rules =
    follow_mouse = 1
    numlock_by_default = true
    sensitivity = 0

    touchpad {
        tap-to-click = true
        natural_scroll = true
    }
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 0.4
    explicit_column_widths = 0.20, 0.5, 0.6, 0.8, 1.0
    direction = right
}

bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
